In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../../data/preprocessExample.csv")

In [3]:
data

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,NaN,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [4]:
data.isna().sum()

Country      1
Age          1
Salary       1
Purchased    0
dtype: int64

Inferential Stats expects

1. Data should be complete
2. Data should be NUMERIC


When using scikitlearn, sklearn has some expectations
1. Ensure the data is represented in the form of Numpy Array for faster processing speed

Seperate my data as features and label

In [11]:
features = data.iloc[:,[0,1,2]].values
labels = data.iloc[:,[3]].values

In [12]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       [nan, 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [13]:
labels

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [20]:
#Imputation
#scikitlearn package

#Step1: Import the relevant package
from sklearn.impute import SimpleImputer

# Imputer class for Country
siForCountry = SimpleImputer(missing_values=np.nan, strategy="most_frequent")

# Fit the object with the data column
siForCountry.fit(features[:, [0]])
features[:,[0]] = siForCountry.transform(features[:, [0]])


In [21]:
siForCountry.statistics_

array(['France'], dtype=object)

In [22]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [23]:
# Age Column

siForAge = SimpleImputer(missing_values=np.nan, strategy="median")
siForAge.fit(features[:,[1]])

features[:, [1]] = siForAge.transform(features[:, [1]])

In [24]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [26]:
# Salary

siForSalary = SimpleImputer(missing_values=np.nan, strategy="mean")

features[:, [2]] = siForSalary.fit_transform(features[:,[2]])

In [27]:
features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['France', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
features[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'France', 'France'], dtype=object)

In [31]:
features[:,0].reshape(-1,1)

array([['France'],
       ['Spain'],
       ['Germany'],
       ['Spain'],
       ['Germany'],
       ['France'],
       ['Spain'],
       ['France'],
       ['France'],
       ['France']], dtype=object)

In [36]:
#Categorical Data Handling
#Recommended to create Dummy Variables
#In Sklearn you can achieve the same using OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

oheContry = OneHotEncoder(sparse_output=False)
fCountry = oheContry.fit_transform(features[:, 0].reshape(-1, 1))

fCountry

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [37]:
featuresFinalSet = np.concatenate((fCountry, features[:,[1,2]]), axis=1)

In [38]:
featuresFinalSet

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [40]:
oheContry.categories_

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [41]:
oheContry.transform(np.array([['France']]))

array([[1., 0., 0.]])

In [43]:
oheContry.inverse_transform(np.array([[1,0,0]]))

array([['France']], dtype=object)

In [44]:
import sklearn
sklearn.__version__

'1.6.1'