In [3]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('../../data/melb_data.csv')

In [6]:
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0


In [9]:
data.isna().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [15]:
featurestat=data.iloc[:, [12,14,15,15]].values
featureDomain=data.iloc[:,[12,14,15,16]].values

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
siForCar = SimpleImputer(missing_values=np.nan, strategy="mean")

In [13]:
siForCar.fit(featurestat[:, [0]])

SimpleImputer()

In [14]:
featurestat[:, [0]] = siForCar.transform(featurestat[:,[0]])

In [19]:
siCarDomain = SimpleImputer(missing_values=np.nan, strategy="constant", fill_value=1)
siCarDomain.fit(featureDomain[:, [0]])
siCarDomain.transform(featureDomain[:,[0]])

array([[1.0],
       [0.0],
       [0.0],
       ...,
       [4.0],
       [5.0],
       [1.0]], shape=(13580, 1), dtype=object)

In [20]:
print(f"Car Stat Calculated: {siForCar.statistics_}")
print(f"Car Domain Calculated: {siCarDomain.statistics_}")

Car Stat Calculated: [1.61007545]
Car Domain Calculated: [1]


In [22]:
siArea = SimpleImputer(missing_values=np.nan, strategy="mean")
featurestat[:,[1]] = siArea.fit_transform(featurestat[:, [1]])

siAreaDomain = SimpleImputer(missing_values=np.nan, strategy="constant", fill_value=80)
featureDomain[:,[1]] = siArea.fit_transform(featureDomain[:, [1]])

In [23]:
siYear = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
featurestat[:, [2]] = siArea.fit_transform(featurestat[:, [2]])

siYearDomain = SimpleImputer(missing_values=np.nan, strategy="constant", fill_value=200)
featureDomain[:, [2]] = siYearDomain.fit_transform(featureDomain[:, [2]])

In [24]:
featurestat

array([[1.00000000e+00, 1.51967650e+02, 1.96468422e+03,            nan],
       [0.00000000e+00, 7.90000000e+01, 1.90000000e+03, 1.90000000e+03],
       [0.00000000e+00, 1.50000000e+02, 1.90000000e+03, 1.90000000e+03],
       ...,
       [4.00000000e+00, 1.51967650e+02, 1.99700000e+03, 1.99700000e+03],
       [5.00000000e+00, 1.57000000e+02, 1.92000000e+03, 1.92000000e+03],
       [1.00000000e+00, 1.12000000e+02, 1.92000000e+03, 1.92000000e+03]],
      shape=(13580, 4))

In [25]:
featureDomain

array([[1.0, 151.96764988779805, 200, 'Yarra'],
       [0.0, 79.0, 1900.0, 'Yarra'],
       [0.0, 150.0, 1900.0, 'Yarra'],
       ...,
       [4.0, 151.96764988779805, 1997.0, nan],
       [5.0, 157.0, 1920.0, nan],
       [1.0, 112.0, 1920.0, nan]], shape=(13580, 4), dtype=object)